### ISSUE TITLE
Endless reconnecting

### ISSUE THREAD

**Issue by vliedel** [dobots/bluenet-lib-android#2]
I'm using BleExt::readTemperature(address, cb), but (I think) when the device doesn't have the temperature characteristic, it keeps on reconnecting.
There seems no way to stop it: calling disconnect() says it's in the wrong state.

**Comment by eggerdo** [comment]
If the device doesn't have the temperature characteristic the service discover would not report it and it would never try to read from temperature characteristic. it is possible that the device cache is old and it thinks that it has a temperature characteristic although it doesn't.
Aside from that, the connection state handling is buggy, so for now I will only check the state and report an error, but still continue the functions.
If you can give me a log file, or show me when it happens I might be able to figure out what's going on.

**Comment by eggerdo** [comment]
closing issue since it hasn't occurred anymore for 2 months. reopen if it happens again
