### ISSUE TITLE
startScan callbacks

### ISSUE THREAD

**Issue by vliedel** [dobots/bluenet-lib-android#3]
When calling BleExt::startScan(), the onError gets called, while it still started scanning.
Also: it's lacking a callback for successfully starting the scan.

**Comment by vliedel** [comment]
Ah, first problem was already solved i see.

**Comment by eggerdo** [comment]
it doesn't need a callback, the function returns true if successfully started, and false otherwise, the error callback is only needed in case it fails later while the scan is running.
